item_teach:
  ros__parameters:
    color_topic: /camera/color/image_raw
    depth_topic: /camera/depth/image_raw
    camera_info_topic: /camera/color/camera_info
    joint_states_topic: /joint_states_robot
    overlay_topic: bin_overlay
    publish_overlay: true
    align_item_z_axis_to_depth_plane: true
    bin_teach_dir: "~/DOBOT_pickn_place/config/bin_teach"
    motion_service_root: /dobot_bringup_ros2/srv
    bin_roi_move_speed_percent: 100
    display_scale: 1.0
    trace_out_to_in: false
