cameras:
- slot: 1
  serial_number: CP1Z842000YW
  camera_name: bin_camera
- slot: 2
  serial_number: CP9JA530001W
  camera_name: robot_camera
orbbec_launch_args:
  device_preset: High Accuracy
  enable_color: true
  enable_depth: true
  depth_registration: true
  align_target_stream: COLOR
  align_mode: SW
  enable_frame_sync: true
  enable_temporal_filter: true
  color_width: 848
  color_height: 480
  color_fps: 30
  depth_width: 848
  depth_height: 480
  depth_fps: 30
  enable_point_cloud: false
