item_detect:
  ros__parameters: &id001
    detection_backend: yolo11_seg_onnx
    item_name: paper_cutlery
    teach_date: 09052026
    class_id: 0
    class_name: paper_cutlery
    color_topic: /camera/color/image_raw
    depth_topic: /camera/depth/image_raw
    camera_info_topic: /camera/color/camera_info
    overlay_topic: bin_overlay
    session_dir: /home/erds/DOBOT_pickn_place/teach/bins_yolo/runtime/paper_cutlery_20260509_191354
    model_dir: /home/erds/DOBOT_pickn_place/teach/bins_yolo/models/item_paper_cutlery_bin_blue_bin_09052026
    model_path: /home/erds/DOBOT_pickn_place/teach/bins_yolo/models/item_paper_cutlery_bin_blue_bin_09052026/best.onnx
    model_onnx_path: /home/erds/DOBOT_pickn_place/teach/bins_yolo/models/item_paper_cutlery_bin_blue_bin_09052026/best.onnx
    model_pt_path: /home/erds/DOBOT_pickn_place/teach/bins_yolo/models/item_paper_cutlery_bin_blue_bin_09052026/best.pt
    dataset_yaml: /home/erds/DOBOT_pickn_place/teach/bins_yolo/runtime/paper_cutlery_20260509_191354/dataset.yaml
    sample_count: 25
    train_epochs: 80
    train_imgsz: 640
    trained_model_path: /home/erds/DOBOT_pickn_place/teach/bins_yolo/models/item_paper_cutlery_bin_blue_bin_09052026/best.pt
    trained_onnx_path: /home/erds/DOBOT_pickn_place/teach/bins_yolo/models/item_paper_cutlery_bin_blue_bin_09052026/best.onnx
    associated_bin_name: blue_bin
    bin_teach_file: /home/erds/DOBOT_pickn_place/teach/bin_teach/blue_bin.yaml
    detection_mode: yolo_depth
    depth_window_mm: 50
    align_item_z_axis_to_depth_plane: true
    joint_states_topic: /joint_states_robot
    teach_joints_deg:
    - 20.66599238429258
    - 22.757991402562
    - -102.91798988259193
    - -8.815002291038521
    - 92.98599847486501
    - 19.891000408376772
    has_teach_joints: true
    roi_points:
    - 212
    - 51
    - 671
    - 34
    - 677
    - 448
    - 219
    - 448
    roi_crop_rect:
    - 212
    - 34
    - 466
    - 415
    depth_plane:
      depth_plane_enabled: true
      depth_plane_a: -0.051844945669
      depth_plane_b: -0.007910904832
      depth_plane_c: 0.706893630126
      depth_plane_reference_depth_m: 0.675620026588
    depth_plane_source: bin_teach
    depth_plane_enabled: true
    depth_plane_a: -0.051844945669
    depth_plane_b: -0.007910904832
    depth_plane_c: 0.706893630126
    depth_plane_reference_depth_m: 0.675620026588
item_yolo:
  ros__parameters: *id001
