item_name: paper_cutlery
class_id: 0
class_name: paper_cutlery
associated_bin_name: blue_bin
session_dir: /home/erds/DOBOT_pickn_place/teach/bins_yolo/runtime/paper_cutlery_20260509_191354
runtime_best_pt: /home/erds/DOBOT_pickn_place/teach/bins_yolo/runtime/paper_cutlery_20260509_191354/models/train/weights/best.pt
runtime_exported_onnx: /home/erds/DOBOT_pickn_place/teach/bins_yolo/runtime/paper_cutlery_20260509_191354/models/train/weights/best.onnx
model_pt_path: /home/erds/DOBOT_pickn_place/teach/bins_yolo/models/item_paper_cutlery_bin_blue_bin_09052026/best.pt
model_onnx_path: /home/erds/DOBOT_pickn_place/teach/bins_yolo/models/item_paper_cutlery_bin_blue_bin_09052026/best.onnx
sample_count: 25
train_epochs: 80
train_imgsz: 640
train_device: cpu
teach_joints_deg:
- 20.66599238429258
- 22.757991402562
- -102.91798988259193
- -8.815002291038521
- 92.98599847486501
- 19.891000408376772
has_teach_joints: true
