item_teach_runtime:
  ros__parameters:
    red_threshold: 69
    green_threshold: 212
    blue_threshold: 142
    color_exposure_us: 0
    depth_exposure_us: 0
    color_exposure_percent: 0
    depth_exposure_percent: 0
    color_exposure_min_us: 1
    color_exposure_max_us: 100
    depth_exposure_min_us: 1
    depth_exposure_max_us: 32000
    rgb_hole_fill_sensitivity: 28
    rgb_mask_dilate_px: 2
    depth_null_fill_sensitivity: 1
    depth_window_mm: 1
    depth_hole_fill_sensitivity: 6
    depth_trim_px: 1
    adaptive_depth_trim_max_add_px: 4
    adaptive_depth_trim_max_height_mm: 138
    blob_tolerance_percent: 16
