tray_detect:
  ros__parameters:
    color_topic: /robot_camera/color/image_raw
    depth_topic: /robot_camera/depth/image_raw
    camera_info_topic: /robot_camera/color/camera_info
    overlay_topic: tray_overlay
    red_threshold: 69
    green_threshold: 13
    blue_threshold: 10
    color_exposure_us: 0
    depth_exposure_us: 0
    color_exposure_percent: 0
    depth_exposure_percent: 0
    color_exposure_min_us: 1
    color_exposure_max_us: 100
    depth_exposure_min_us: 1
    depth_exposure_max_us: 32000
    depth_threshold_mm: 10
    detection_mode: rgb
    ray_step_px: 6
    depth_edge_offset_px: 5
    previous_color_percent: 89
    horizontal_ray_count: 38
    vertical_ray_count: 61
    outlier_sensitivity: 95
    detect_black_to_white: true
    trace_out_to_in: true
    tray_plane_enabled: true
    tray_plane_a: 0.01053759485677605
    tray_plane_b: 0.013031291299558526
    tray_plane_c: 0.31436839129356808
    tray_plane_reference_depth_m: 0.32566328316318743
    tray_plane_roi: [239, 67, 494, 427]
    tray_plane_roi_points: [239, 76, 475, 67, 494, 418, 263, 427]
    roi_points: [134, 7, 627, 3, 656, 474, 120, 478]
    tray_name: brown_tray
    teach_date: 2026-06-09
    teach_joints_deg: [-50.58303365252732, 8.6592977954035373, -119.1809748346675, 17.463624656326306, -268.50063628901353, 41.283374082158502]
    tray_dimension_source: rgb_corners_on_tray_plane
    tray_width_mm: 194.05429428028555
    tray_height_mm: 276.95742441626294
