item_teach_yolo:
  ros__parameters:
    color_topic: /robot_camera/color/image_raw
    joint_states_topic: /joint_states_robot
    item_name: item
    depth_topic: /robot_camera/depth/image_raw
    camera_info_topic: /robot_camera/color/camera_info
    overlay_topic: bin_overlay
    sam2_config: configs/sam2.1/sam2.1_hiera_t.yaml
    train_epochs: 80
    train_imgsz: 640
    train_device: cpu
    display_scale: 1.0
    live_view_enabled: true
    overlay_enabled: true
